### PR TITLE
added childcare to things to help meetups with

### PR DESCRIPTION
**Pull request by krantzinator**

### CODE REVIEW

**Comment by krantzinator** [comment]
I foresee being able to help with this in the future, although I can't at this exact moment. But wanted it to be on the list in the meantime, in case someone else could also step up!

**Comment by davekiss** [comment]
Thanks! I don't have any children, but I do often hear that those rascals can frequently prevent attendance.

I'm unsure if this falls in the scope of what this organization should or could be liable for. I'm going to leave this PR open for others to weigh in on who may have some sort of experience with other groups that are offering this or who may otherwise hold an opinion on the matter.

**Comment by stevenjackson** [comment]
As a parent, this is my primary blocker from attending 6 meetups a month.  I love meetups but $60/night for babysitting is out of the question.

Liability is certainly an issue.  But, it would take a larger-than-meetup-sized-organization to take that on, which certainly makes it appealing to put under an umbrella.

**Comment by krantzinator** [comment]
Liability could be covered with signing forms, yeah? There are also organizations like College Nannies and Tutors that prescreen caregivers (drug tests, background checks), and have a large network of caregivers who could likely respond to last-minute requests (ex. if childcare is known to be needed only in the days leading up to a specific meetup).

**Comment by anthony-coble** [comment]
I love this idea, and it could be a big help for me as well. Ideas like this are what I think is the "Ohio flavor" for an organization like this.

**Comment by krantzinator** [comment]
This appears to have gone stale. Closing.

**Pull request closed without merging**
